const MONSTERS = {
    'slime': { name: 'Slime', powerReq: 10, dropChance: 0.20, class: 'lemah' },
    'bat': { name: 'Bat', powerReq: 20, dropChance: 0.21, class: 'lemah' },
    'rat': { name: 'Rat', powerReq: 30, dropChance: 0.22, class: 'lemah' },
    'spider': { name: 'Spider', powerReq: 50, dropChance: 0.23, class: 'lemah' },
    'snake': { name: 'Snake', powerReq: 75, dropChance: 0.24, class: 'lemah' },
    'goblin': { name: 'Goblin', powerReq: 100, dropChance: 0.25, class: 'lemah' },
    'skeleton': { name: 'Skeleton', powerReq: 150, dropChance: 0.26, class: 'lemah' },
    'zombie': { name: 'Zombie', powerReq: 200, dropChance: 0.27, class: 'lemah' },
    'wolf': { name: 'Wolf', powerReq: 250, dropChance: 0.28, class: 'lemah' },
    'boar': { name: 'Boar', powerReq: 300, dropChance: 0.29, class: 'lemah' },
    'bear': { name: 'Bear', powerReq: 350, dropChance: 0.30, class: 'lemah' },
    'bandit': { name: 'Bandit', powerReq: 400, dropChance: 0.31, class: 'lemah' },
    'rogue': { name: 'Rogue', powerReq: 500, dropChance: 0.32, class: 'lemah' },
    'cultist': { name: 'Cultist', powerReq: 600, dropChance: 0.33, class: 'lemah' },
    'imp': { name: 'Imp', powerReq: 700, dropChance: 0.34, class: 'lemah' },
    'harpy': { name: 'Harpy', powerReq: 800, dropChance: 0.35, class: 'lemah' },
    'murloc': { name: 'Murloc', powerReq: 900, dropChance: 0.36, class: 'lemah' },
    'kobold': { name: 'Kobold', powerReq: 1000, dropChance: 0.37, class: 'lemah' },
    'gnome': { name: 'Gnome', powerReq: 1200, dropChance: 0.38, class: 'lemah' },
    'pixie': { name: 'Pixie', powerReq: 1500, dropChance: 0.39, class: 'lemah' },
    'orc': { name: 'Orc', powerReq: 2500, dropChance: 0.30, class: 'kuat' },
    'troll': { name: 'Troll', powerReq: 3000, dropChance: 0.32, class: 'kuat' },
    'ogre': { name: 'Ogre', powerReq: 4000, dropChance: 0.33, class: 'kuat' },
    'minotaur': { name: 'Minotaur', powerReq: 5000, dropChance: 0.34, class: 'kuat' },
    'cyclops': { name: 'Cyclops', powerReq: 7500, dropChance: 0.36, class: 'kuat' },
    'golem': { name: 'Golem', powerReq: 10000, dropChance: 0.38, class: 'kuat' },
    'gargoyle': { name: 'Gargoyle', powerReq: 15000, dropChance: 0.39, class: 'kuat' },
    'wraith': { name: 'Wraith', powerReq: 20000, dropChance: 0.40, class: 'kuat' },
    'banshee': { name: 'Banshee', powerReq: 25000, dropChance: 0.42, class: 'kuat' },
    'vampire': { name: 'Vampire', powerReq: 30000, dropChance: 0.43, class: 'kuat' },
    'werewolf': { name: 'Werewolf', powerReq: 40000, dropChance: 0.45, class: 'kuat' },
    'chimera': { name: 'Chimera', powerReq: 50000, dropChance: 0.46, class: 'kuat' },
    'manticore': { name: 'Manticore', powerReq: 60000, dropChance: 0.48, class: 'kuat' },
    'basilisk': { name: 'Basilisk', powerReq: 75000, dropChance: 0.49, class: 'kuat' },
    'hydra': { name: 'Hydra', powerReq: 90000, dropChance: 0.51, class: 'kuat' },
    'griffon': { name: 'Griffon', powerReq: 100000, dropChance: 0.52, class: 'kuat' },
    'wyvern': { name: 'Wyvern', powerReq: 120000, dropChance: 0.54, class: 'kuat' },
    'drake': { name: 'Drake', powerReq: 135000, dropChance: 0.55, class: 'kuat' },
    'dragon': { name: 'Dragon', powerReq: 150000, dropChance: 0.57, class: 'kuat' },
    'behemoth': { name: 'Behemoth', powerReq: 175000, dropChance: 0.58, class: 'kuat' },
    'leviathan': { name: 'Leviathan', powerReq: 200000, dropChance: 0.50, class: 'boss' },
    'kraken': { name: 'Kraken', powerReq: 250000, dropChance: 0.52, class: 'boss' },
    'cerberus': { name: 'Cerberus', powerReq: 300000, dropChance: 0.54, class: 'boss' },
    'fenrir': { name: 'Fenrir', powerReq: 400000, dropChance: 0.56, class: 'boss' },
    'jormungandr': { name: 'Jormungandr', powerReq: 500000, dropChance: 0.58, class: 'boss' },
    'titan': { name: 'Titan', powerReq: 750000, dropChance: 0.60, class: 'boss' },
    'colossus': { name: 'Colossus', powerReq: 1000000, dropChance: 0.62, class: 'boss' },
    'archdemon': { name: 'Archdemon', powerReq: 1250000, dropChance: 0.64, class: 'boss' },
    'archangel': { name: 'Archangel', powerReq: 1500000, dropChance: 0.66, class: 'boss' },
    'lich-king': { name: 'Lich King', powerReq: 1750000, dropChance: 0.68, class: 'boss' },
    'death-knight': { name: 'Death Knight', powerReq: 2000000, dropChance: 0.70, class: 'boss' },
    'chaos-elemental': { name: 'Chaos Elemental', powerReq: 2500000, dropChance: 0.72, class: 'boss' },
    'void-terror': { name: 'Void Terror', powerReq: 3000000, dropChance: 0.74, class: 'boss' },
    'star-spawn': { name: 'Star Spawn', powerReq: 3500000, dropChance: 0.76, class: 'boss' },
    'ancient-dragon': { name: 'Ancient Dragon', powerReq: 4000000, dropChance: 0.78, class: 'boss' },
    'primordial-behemoth': { name: 'Primordial Behemoth', powerReq: 4500000, dropChance: 0.80, class: 'boss' },
    'elder-god': { name: 'Elder God', powerReq: 5000000, dropChance: 0.82, class: 'boss' },
    'abyssal-lord': { name: 'Abyssal Lord', powerReq: 6000000, dropChance: 0.84, class: 'boss' },
    'cosmic-entity': { name: 'Cosmic Entity', powerReq: 8000000, dropChance: 0.86, class: 'boss' },
    'creator': { name: 'Creator', powerReq: 10000000, dropChance: 0.88, class: 'boss' },
};
