const { pickRandom, randomInt } = require('../lib/functions');

module.exports = [
    { name: 'coba', category: 'fun', desc: 'Coba-coba', async execute({ m }) { await m.reply(pickRandom(['Coba aja dulu!','Jangan coba-coba!','Cobain aja, siapa takut!','Hmm... coba lagi nanti deh.'])); } },
    { name: 'dadu', category: 'fun', desc: 'Lempar dadu', async execute({ m }) { const n = randomInt(1,6); const e = ['','⚀','⚁','⚂','⚃','⚄','⚅']; await m.reply(`🎲 Kamu dapat: ${e[n]} (${n})`); } },
    { name: 'bisakah', category: 'fun', desc: 'Tanya bisakah', usage: '(text)', async execute({ m, text }) { if (!text) return m.reply('❌ .bisakah [pertanyaan]'); const answers = ['Bisa dong! 💪','Nggak bisa 😂','Mungkin bisa...','Coba aja dulu!','100% BISA!','Kayaknya nggak deh...']; await m.reply(`❓ *${text}*\n\n🎱 ${pickRandom(answers)}`); } },
    { name: 'apakah', category: 'fun', desc: 'Tanya apakah', usage: '(text)', async execute({ m, text }) { if (!text) return m.reply('❌ .apakah [pertanyaan]'); const pct = randomInt(0,100); await m.reply(`❓ *${text}*\n\n🎱 Menurut bot: *${pct}%* ${pct > 50 ? 'IYA!' : 'TIDAK!'}`); } },
    { name: 'kapan', category: 'fun', desc: 'Tanya kapan', usage: '(text)', async execute({ m, text }) { if (!text) return m.reply('❌ .kapan [pertanyaan]'); const times = ['Besok','Lusa','Minggu depan','Bulan depan','Tahun depan','Nggak akan pernah 😂','Sekarang juga!','Kalau sudah waktunya','100 tahun lagi']; await m.reply(`❓ Kapan *${text}*?\n\n🎱 ${pickRandom(times)}`); } },
    { name: 'siapa', category: 'fun', desc: 'Tanya siapa', usage: '(text)', async execute({ sock, m, text }) { if (!text) return m.reply('❌ .siapa [pertanyaan]'); if (m.isGroup) { const meta = await sock.groupMetadata(m.chat); const random = pickRandom(meta.participants); await sock.sendMessage(m.chat, { text: `❓ *${text}*\n\n🎱 Jawabannya: @${random.id.split('@')[0]}`, mentions: [random.id] }, { quoted: m.raw }); } else { await m.reply(`❓ *${text}*\n\n🎱 Jawabannya: Kamu sendiri! 😂`); } } },
    { name: 'rate', category: 'fun', desc: 'Rating sesuatu', usage: '(reply/text)', async execute({ m, text }) { const t = text || m.quoted?.body || 'ini'; await m.reply(`⭐ *RATE*\n\n📝 ${t}\n🎯 Rating: *${randomInt(1,100)}/100*`); } },
    { name: 'jodohku', category: 'fun', desc: 'Cek jodoh', async execute({ sock, m }) { if (m.isGroup) { const meta = await sock.groupMetadata(m.chat); const r = pickRandom(meta.participants); await sock.sendMessage(m.chat, { text: `💕 Jodoh kamu adalah @${r.id.split('@')[0]}!\n❤️ Kecocokan: ${randomInt(50,100)}%`, mentions: [r.id] }, { quoted: m.raw }); } else { await m.reply(`💕 Jodoh kamu belum ditemukan... coba di grup!`); } } },
    { name: 'cekmati', aliases: ['cekumur'], category: 'fun', desc: 'Cek umur mati (fun)', usage: '(nama)', async execute({ m, text }) { if (!text) return m.reply('❌ Masukkan nama!'); await m.reply(`💀 *CEK MATI*\n\n👤 ${text}\n⏰ Akan meninggal di umur: *${randomInt(60,120)} tahun*\n📅 Penyebab: ${pickRandom(['Keselek micin','Kebanyakan scroll TikTok','Tertidur selamanya','Terlalu ganteng/cantik','Overdosis kebahagiaan'])}`); } },
    { name: 'ceksifat', category: 'fun', desc: 'Cek sifat', async execute({ m }) { const sifat = ['Baik','Pemalas','Rajin','Pelit','Dermawan','Pemarah','Sabar','Lucu','Serius','Romantis','Cuek','Perhatian']; const list = []; for (let i=0; i<5; i++) list.push(`${sifat[randomInt(0,sifat.length-1)]}: ${randomInt(10,100)}%`); await m.reply(`🔮 *CEK SIFAT*\n\n${list.join('\n')}`); } },
    { name: 'cekjodoh', aliases: ['cekcocok'], category: 'fun', desc: 'Cek kecocokan', usage: '(nama lu)', async execute({ m, text }) { if (!text) return m.reply('❌ .cekkhodam namaKamu'); await m.reply(`💑 *CEK KHODAM*\n\n👤 ${text}\n🔮 Khodam: *${pickRandom(['Macan Putih','Naga Hitam','Elang Emas','Harimau Sumatera','Kuda Terbang','Buaya Darat','Ular Tangga','WiFi Tetangga','Kucing Oren','Ayam Jago'])}*`); } },
    { name: 'jadian', category: 'fun', desc: 'Pasangkan random', async execute({ sock, m }) { if (!m.isGroup) return m.reply('❌ Hanya di grup!'); const meta = await sock.groupMetadata(m.chat); if (meta.participants.length < 2) return m.reply('❌ Member terlalu sedikit!'); const a = pickRandom(meta.participants); let b; do { b = pickRandom(meta.participants); } while (b.id === a.id); await sock.sendMessage(m.chat, { text: `💕 *JADIAN*\n\n@${a.id.split('@')[0]} ❤️ @${b.id.split('@')[0]}\n💘 Kecocokan: ${randomInt(50,100)}%`, mentions: [a.id, b.id] }, { quoted: m.raw }); } },
    { name: 'fitnah', category: 'fun', desc: 'Fitnah seseorang', async execute({ sock, m }) { if (!m.isGroup) return m.reply('❌ Hanya di grup!'); const meta = await sock.groupMetadata(m.chat); const r = pickRandom(meta.participants); const fitnah = ['diam-diam suka sama admin','sering nge-stalk mantan','kalau makan selalu minta traktir','pernah nangis gara-gara ditinggal kucing','suka ngomong sendiri depan kaca']; await sock.sendMessage(m.chat, { text: `🗣️ *FITNAH*\n\nKatanya @${r.id.split('@')[0]} ${pickRandom(fitnah)} 😂`, mentions: [r.id] }, { quoted: m.raw }); } },
    { name: 'halah', category: 'fun', desc: 'Halah', usage: '(text)', async execute({ m, text }) { await m.reply(`hAlAh ${text || 'apaansih'}`); } },
    { name: 'hilih', category: 'fun', desc: 'Hilih', usage: '(text)', async execute({ m, text }) { await m.reply(`hIlIh ${text || 'apaansih'}`); } },
    { name: 'huluh', category: 'fun', desc: 'Huluh', usage: '(text)', async execute({ m, text }) { await m.reply(`hUlUh ${text || 'apaansih'}`); } },
    { name: 'heleh', category: 'fun', desc: 'Heleh', usage: '(text)', async execute({ m, text }) { await m.reply(`hElEh ${text || 'apaansih'}`); } },
    { name: 'holoh', category: 'fun', desc: 'Holoh', usage: '(text)', async execute({ m, text }) { await m.reply(`hOlOh ${text || 'apaansih'}`); } },
    { name: 'kerangajaib', category: 'fun', desc: 'Kerang ajaib', usage: '(text)', async execute({ m, text }) { if (!text) return m.reply('❌ Tanyakan sesuatu!'); await m.reply(`🐚 *KERANG AJAIB*\n\n❓ ${text}\n🎱 ${pickRandom(['Mungkin suatu hari','Tidak','Tidak juga','Coba tanya lagi','Bisa jadi','Benar','Salah','Mungkin','Tidak mungkin'])}`); } },
];
